# Generated by Django 3.1.7 on 2021-05-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='description_responsibility',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description_requirement',
        ),
    ]
